// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiycronhneufnvnissus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9peWNyb25obmV1Zm52bmlzc3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDk3NjQsImV4cCI6MjA2NzAyNTc2NH0.lweGKRKDgybRCcoGMVoJ0Wzw0plHsNy3O4RbV0MrQLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});